### Site info:
title: B-SKY Lab #Freshman21
tagline: 制作物や技術メモを公開していきます #Another Jekyll theme, Freshman twenty-first
author: B-SKY Lab #Lijia Yu
#email: #hello@gmail.com #yu@lijiayu.net
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
baseurl: "/b-sky-lab" # the subpath of your site, e.g. /blog
url: "https://kim-xps12.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#keywords: "Jekyll, theme, Freshman21"
locale: ja_JP

### Personal info and site tools info:
twitter_username: B_SKY_Lab
github_username:  kim-xps12
disqus_shortname: B-SKY Lab
favicon:     "/favicon.png"
aboutme: おっはもーにん。このブログでは趣味の工作や研究で制作した物たち、ハマリどころだった技術メモなどを載せていきます。過去作たちも順次アップロード予定です、いえい。 # these are shown on aboutme-sidebar.
aboutme_photo: "/images/icon_mini.jpg" #https://i.imgur.com/Mdc4szJl.jpg# your photo.
google_analytics_key: #UA-182992327-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "jp" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).
timezone: Asia/Tokyo

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
      Links: "links"

    jp:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Home: "Home"
      Google_search: "サイト内検索"
      About: "About"
      Links: "相互リンク"
      #Guestbook: "Guestbook"
      #Subscribe: "Subscribe"

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins:
  - jekyll-feed
  #- jekyll-paginate-v2
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-seo-tag
paginate: 5
#pagination:
#  enabled: true
#  per_page: 5
#  permalink: '/page/:num/'
#  sort_field: 'date'
#  sort_reverse: true
excerpt_separator: <!-- more -->
search: true
