# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: B-SKY Lab
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/b-sky-lab" # the subpath of your site, e.g. /blog
url: "https://kim-xps12.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  kim-xps12

# Social Sharing
twitter:
  username               : &twitter "B_SKY_Lab"
facebook:
  username               : &facebook ""
  app_id                 :
  publisher              :
og_image                 : "site-logo.png" # Open Graph/Twitter default site image

author:
    github : kim-xps12
    
# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
search: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
        sidebar:
        nav: "docs"
plugins:
  - jekyll-feed
#  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

collections:
  my_tags:
    output: true
    permalink: /tag/:name/
    filepath: /tag
    layout: home

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-LX0RWLGPK6"
    anonymize_ip: false # default

timezone: Asia/Tokyo

permalink: /:categories/:year/:month/
#permalink: /:categories/:year/:month/:title.html
pagination:
  enabled: true
  collection: 'posts'
  permalink: '/page/:num/'
  per_page: 4
  sort_reverse: true
  sort_field: 'date'


#paginate: 5
    #  - title: "Title"
    #    image: http://placehold.it/350x250
    #    image_alt: "image"
    #    text: "Some text here."
    #  - title: "Another Title"
    #    text: "More text here."
    #    nav: sidebar-sample
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
